name = "neural-fortran"
version = "0.24.0"
license = "MIT"
author = "Milan Curcic"
maintainer = "mcurcic@miami.edu"
copyright = "Copyright 2018-2026, neural-fortran contributors"

[preprocess]
[preprocess.cpp]
